Frederick888/external-editor-revived

src/model/thunderbird.rs
This field is only available from Thunderbird 91.3.1 [1].
[1] https://webextension-api.thunderbird.net/en/91/compose.html#compose-composedetails
No
- OS: 
Closes #20
=> feat(host): Skip relatedMessageId if null

extension/options/options.html, extension/options/options.js
commit 3d802fcc3c40dd3113ebb8492ca289daba5c5890
Author: Frederick Zhang <frederick888@tsundere.moe>
Date:   Sat Jul 9 23:16:38 2022 +1000
feat(ext): Kitty macos_quit_when_last_window_closed
Kitty mimics macOS's built-in Console's behaviour by default, where it
doesn't quit when the last window is closed. This then requires users to
manually end Kitty after exiting the editor before ExtEditorR can report
back to Thunderbird.
Hence adding macos_quit_when_last_window_closed=yes to command template.
Under Linux this is harmless.
commit 86763e6d5219df8833db93ff4d8b1f804bc80d02
Author: Frederick Zhang <frederick888@tsundere.moe>
Date:   Sat Jul 9 23:48:52 2022 +1000
feat(ext): Prompt to sync with upstream template
Since we try not to touch users' existing settings when updating, this
introduces …
=> Kitty macos_quit_when_last_window_closed=yes by default; Add template migration UI

extension/background.js, src/model/messaging.rs
Some people are confused by the old name, as obviously you can save the
file for arbitrary times while you are in your editor.
No. (If user's in the middle of editing an email, and they overwrites
the messaging host, they'll have to reload which will break the session
anyway. They should at least wait until finishing editing all emails
before reloading.)
- OS: 
=> feat(host): Rename Send-On-Save to Send-On-Exit

extension/background.js, extension/options/options.html, extension/options/options.js, src/model/messaging.rs
Add some cosmetic help message headers. Can be switched off in settings.
No
- OS: 
Closes #24
=> feat: Add help message headers

extension/manifest.json
Ctrl-E to start external editor.
For now this is the only shortcut.
Later when I get onto #6 I can try adding Shift-Ctrl-E or something for
save-on-exit by default.
No
- OS: 
Closes #22
Closes #18
=> feat(ext): Add Ctrl-E shortcut for compose action

extension/background.js, src/model/messaging.rs
A warning notification is shown as well.
In the future this should be the general rule of handling non-critical
issues.
No
- OS: 
=> feat: Cancel send-on-exit in case of unknown headers

extension/background.js, extension/manifest.json
Like Shift-click. Only works in message compose window.
On Mac this is probably Command-Shift-E as usual. will test
No
- OS: Linux
- Thunderbird version: 91
=> feat(ext): Ctrl-Shift-E to edit with Send-On-Exit

src/model/messaging.rs
The body was trimmed since it kept adding blank lines to the end of my
emails. I thought it was a Neovim fileformat=dos issue but it turned out
the culprit was an writeln!() by mistake when writing temporary files.
Hence replacing the writeln!() with write!() and stopping trimming
bodies.
- OS: 
=> fix(host): Stop unnecessarily trimming email bodies

src/model/messaging.rs, src/model/thunderbird.rs
- feat(host): Conciser help headers at the bottom
- feat(host): Add placeholders for absent headers
- refactor(host): Improve recipient list merging
No
- OS: Linux
- Thunderbird version: 91
Closes #51
=> Improve headers in temporary eml files

src/model/messaging.rs, src/model/thunderbird.rs, src/util.rs
According to [1], CRLF should be used in EML files regardless of
platform. Thunderbird also commits to this standard for better
interoperability [2].
And Vim/Neovim actually set fileformat=dos by default for EML files even
under Linux/macOS, hence sending CRLF to Thunderbird directly shouldn't
be an issue either.
[1] https://datatracker.ietf.org/doc/html/rfc2822
[2] https://bugzilla.mozilla.org/show_bug.cgi?id=503271
No (but slightly risky?).
Actually a small test under Linux showed that even if I send LF to
Thunderbird, when the email is sent out, they are all converted to CRLF.
So even cases like sending Git patches should be ok, as users must've
been dealing with CRLF using Git's CRLF auto conversion already.
- OS: Linux
- Thunderbird version: 91
Closes #53
=> feat(host): CRLF in temporary EML files

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/gh-ph.yml, src/main.rs, src/model/thunderbird.rs
[1] https://github.com/Frederick888/gh-ph
Got this clippy warning on Rust nightly.
[1] https://rust-lang.github.io/rust-clippy/master/index.html#needless_borrow
No.
- OS: 
=> ci: Use gh-ph to add commit history to PR bodies

src/model/thunderbird.rs
According to [1], Thunderbird 102 under Windows is also sending LF as
opposed to CRLF in Thunderbird 91 [2].
[1] https://github.com/Frederick888/external-editor-revived/issues/62
[2] https://github.com/Frederick888/external-editor-revived/issues/53
No.
- OS: 
Closes #62
=> fix(host): Support both LF & CRLF under Windows

.github/workflows/ci.yml, .github/workflows/release.yml
=> ci: Resolve set-output & Node deprecation warnings

Cargo.lock, Cargo.toml, src/main.rs
web-ext-native-messaging [1] has been yanked. It seems that the author
simply wanted to migrate away from GitHub to [2]. There was no security
issues involved.
[1] https://crates.io/crates/web-ext-native-messaging
[2] https://git.bauke.xyz/Holllo/webextension-native-messaging
No.
- OS: 
=> chore(host): Migrate to webextension-native-messaging

Cargo.lock, Cargo.toml, src/model/messaging.rs
While input from Thunderbird is always sanitised, users can add random
things into the temporary EML file. And when there are invalid UTF-8
sequences in the file, read_line() fails as it cannot convert it to
String.
Since Thunderbird sanitises outgoing emails as well, we don't need to
bother sending the very original contents to Thunderbird. Simply
from_utf8_lossy() should suffice.
No.
- OS: Linux
- Thunderbird version: 102.3.3
Fixes #65
=> fix(host): Fix crashes when EML has invalid UTF-8

Cargo.lock, Justfile
itoa v1.0.3 -> v1.0.4
proc-macro2 v1.0.44 -> v1.0.47
serde_json v1.0.85 -> v1.0.87
syn v1.0.101 -> v1.0.102
unicode-ident v1.0.4 -> v1.0.5
No
- OS: 
=> Upgrade dependencies

src/main.rs, src/model/messaging.rs
[1] https://rust-lang.github.io/rust-clippy/master/index.html#uninlined_format_args
No
- OS: 
=> style(host): Inline format!() arguments

src/main.rs
Since [1] has been silent for quite a while, I don't see Thunderbird's
developer docs get updated any time soon. So better to hide the link
under macOS to avoid confusion.
[1] https://github.com/thundernest/developer-docs/issues/147
No
- OS: 
=> feat(host): Hide manifest wiki link under macOS

extension/background.js, extension/options/options.html, extension/options/options.js, src/main.rs, src/model/messaging.rs, src/util.rs
No
- OS: Linux
- Thunderbird version: 102.7.0
Closes #81
=> feat: Allow customising temporary directory for EMLs

Cargo.lock, Cargo.toml, src/model/messaging.rs
anyhow v1.0.66 -> v1.0.68
itoa v1.0.4 -> v1.0.5
proc-macro2 v1.0.47 -> v1.0.50
quote v1.0.21 -> v1.0.23
ryu v1.0.11 -> v1.0.12
serde v1.0.149 -> v1.0.152
serde_derive v1.0.149 -> v1.0.152
serde_json v1.0.89 -> v1.0.91
syn v1.0.105 -> v1.0.107
thiserror v1.0.37 -> v1.0.38
thiserror-impl v1.0.37 -> v1.0.38
unicode-ident v1.0.5 -> v1.0.6
No
- OS: Linux
- Thunderbird version: 102.7.0
=> Upgrade host dependencies

extension/background.js, src/main.rs, src/model/messaging.rs
Previously if anything went wrong in the messaging host, we only showed
a notification to the user and the user was stuck with a greyed out
ExtEditorR button.
However in some cases, the error may be fixed by updating ExtEditorR's
and/or the editor's configurations, e.g.
- Host cannot create the temporary EML file
- Host cannot write to the temporary EML file
- Host cannot start the editor
Now when such an error arises, we re-enable ExtEditorR's button and
clear out all received messages for the compose window (which should be
empty in the first place).
For other errors, we keep the button greyed out to avoid overwriting any
data. And there are also errors like version mismatch where users have
to reload ExtEditorR.
No
- OS: Linux
- Thunderbird version: 102.7.0
=> feat: Reset compose state if error is recoverable

Cargo.lock
anyhow v1.0.68 -> v1.0.69
proc-macro2 v1.0.50 -> v1.0.51
serde_json v1.0.91 -> v1.0.93
No
- OS: Linux
- Thunderbird version: 102
=> chore(host): Upgrade dependencies

.github/workflows/ci.yml, .github/workflows/release.yml
=> ci: Use github.sha as commit hash

.github/workflows/ci.yml, Justfile, src/model/messaging.rs, src/model/thunderbird.rs
So that it reports code that's used only in tests as unused.
This is a new option added in Thunderbird 102.
Note that we should avoid serialising this field if the user did not
change it [1]:
If the value has not been modified, selecting a different identity
will load the default value of the new identity.
[1] https://webextension-api.thunderbird.net/en/stable/compose.html#composedetails
No
- OS: Linux
- Thunderbird version: 102.8.0
Closes #94
=> feat: Support attaching vCard

src/model/messaging.rs, src/model/thunderbird.rs
No
- OS: Linux
- Thunderbird version: 102.8.0
Closes #97
=> feat(host): Support delivery status notification

Justfile, src/model/messaging.rs, src/model/thunderbird.rs
No
- OS: Linux
- Thunderbird version: 102.8.0
Closes #98
=> feat(host): Support return receipt

extension/background.js, extension/options/options.html, extension/options/options.js, src/model/messaging.rs, src/model/thunderbird.rs
No. Custom headers are disabled by default.
- OS: Linux
- Thunderbird version: 102.9.0
Closes #96
=> Support custom headers

src/model/thunderbird.rs
There are some unexpected side effects according to [1], where other
unrelated headers like In-Reply-To, References, etc. were purged. This
minimises the blast radius.
[1] https://github.com/Frederick888/external-editor-revived/issues/110
No
- OS: Linux
- Thunderbird version: 102
=> feat: Do not serialise empty custom headers array

Cargo.lock, Cargo.toml
aho-corasick v0.7.20 -> v1.1.2
anyhow v1.0.70 -> v1.0.75
base64 v0.21.0 -> v0.21.5
byteorder v1.4.3 -> v1.5.0
either v1.8.1 -> v1.9.0
itoa v1.0.6 -> v1.0.9
memchr v2.5.0 -> v2.6.4
num-traits v0.2.15 -> v0.2.17
proc-macro2 v1.0.54 -> v1.0.69
quote v1.0.26 -> v1.0.33
regex v1.7.3 -> v1.10.2
regex-syntax v0.6.29 -> v0.8.2
rustversion v1.0.12 -> v1.0.14
ryu v1.0.13 -> v1.0.15
serde v1.0.159 -> v1.0.189
serde_derive v1.0.159 -> v1.0.189
serde_json v1.0.95 -> v1.0.107
syn v2.0.12 -> v2.0.38
thiserror v1.0.40 -> v1.0.50
thiserror-impl v1.0.40 -> v1.0.50
unicode-ident v1.0.8 -> v1.0.12
No
- OS: 
=> upgrade dependencies 2023 10 25

extension/options/options.html, extension/options/options.js
This adds a new option for GNOME Terminal in extension preferences. GNOME Terminal is one of the more popular terminal emulators on Linux, so I think it would be nice to have it as an option.
No. This just adds a new option to the extension preferences. Existing options remain unchanged.
- OS: Linux
- Thunderbird version: 115.2.2
=> feat(ext): Add GNOME Terminal to options

src/model/messaging.rs
No
- OS: Linux
- Thunderbird version: 115.4.1
=> feat(host): List priority / delivery format options in help lines

Cargo.lock, Cargo.toml, extension/background.js, extension/options/options.html, extension/options/options.js, src/model/messaging.rs, src/util.rs, src/util/meta_header.rs
The extension setting only affects the default presentation. Meta header
parsing is always enabled.
To use the X-ExtEditorR meta header as a literal custom header, escape
it by prepending an 'X-ExtEditorR-'.
That is, to send an 'X-ExtEditorR: foo' custom header, one can use
either 'X-ExtEditorR: X-ExtEditorR: foo' or 'X-ExtEditorR-X-ExtEditorR:
foo'; to send an 'X-ExtEditorR-Hello: foo', one can use either
'X-ExtEditorR: X-ExtEditorR-Hello: foo' or
'X-ExtEditorR-X-ExtEditorR-Hello: foo'.
No.
Previously `X-ExtEditorR*` could be custom headers directly, but custom
header has not been released.
- OS: Linux / macOS
- Thunderbird version: 115.4.2
Closes #108
=> feat: Support X-ExtEditorR meta header

src/model/messaging.rs
=> style(host): Remove some unneeded references

src/model/messaging.rs
No
- OS: Linux
- Thunderbird version: 115
=> fix(host): Don't add unescaped meta headers to custom headers

src/model/messaging.rs, src/model/thunderbird.rs
No
- OS: Linux
- Thunderbird version: 115
=> fix(host): Don't use meta header if the value has commas or colons

extension/background.js, src/main.rs, src/model/messaging.rs
No.
- OS: Linux
- Thunderbird version: 115.6.1
Closes #109
=> feat: Notification to prompt users to download hosts

extension/background.js, src/main.rs, src/model/messaging.rs
Since I realised that I had to check bypassVersionCheck in the extension
anyway, it's cleaner to just remove it from the host.
No
- OS: Linux
- Thunderbird version: 115.7.0
=> refactor: Simplify version check in ping-pong

.github/workflows/ci.yml
[1] https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/
[2] https://github.com/styfle/cancel-workflow-action/commit/00326b1bd66ff5f5cc497a20eb0e6a95d9bdc5f7
No
- OS: 
=> ci: Bump styfle/cancel-workflow-action to 0.12.1

Cargo.lock, Cargo.toml
aho-corasick v1.1.2 -> v1.1.3
anstyle v1.0.4 -> v1.0.8
anyhow v1.0.79 -> v1.0.86
heck v0.4.1 -> v0.5.0
itoa v1.0.10 -> v1.0.11
lazy_static v1.4.0 -> v1.5.0
memchr v2.7.1 -> v2.7.4
predicates v3.1.0 -> v3.1.2
predicates-core v1.0.6 -> v1.0.8
predicates-tree v1.0.9 -> v1.0.11
proc-macro2 v1.0.78 -> v1.0.86
quote v1.0.35 -> v1.0.36
regex v1.10.3 -> v1.10.6
regex-automata v0.4.5 -> v0.4.7
regex-syntax v0.8.2 -> v0.8.4
rustversion v1.0.14 -> v1.0.17
ryu v1.0.16 -> v1.0.18
serde v1.0.196 -> v1.0.207
serde_derive v1.0.196 -> v1.0.207
serde_json v1.0.113 -> v1.0.124
strum v0.26.1 -> v0.26.3
strum_macros v0.26.1 -> v0.26.4
syn v2.0.48 -> v2.0.74
thiserror v1.0.56 -> v1.0.63
thiserror-impl v1.0.56 -> v1.0.63
- OS: Linux
- Thunderbird version: 115.14.0
=> Upgrade dependencies 2024 08 15

src/model/thunderbird.rs
[1] https://rust-lang.github.io/rust-clippy/master/index.html#needless_lifetimes
No
- OS: 
=> style(ext): Elided explicit lifetime

.github/workflows/ci.yml, .gitignore, extension/.jsbeautifyrc, extension/options/options.html, extension/package.json, extension/tsfmt.json
Using typescript-formatter for JavaScript and js-beautify for HTML. This
should be quite close to my vtsls + vscode-html-languageservice (which
uses js-beautify [1]) Neovim setup, as well as VSCode out of the box.
[1] https://code.visualstudio.com/docs/languages/html#_formatting
No
- OS: 
=> ci(ext): Check extension formats in Actions

src/main.rs
[1] https://rust-lang.github.io/rust-clippy/master/index.html#io_other_error
No
- OS: Linux
- Thunderbird version: 141.0
=> style(host): Use io::Error::other() as per clippy

extension/options/options.html
No
- OS: Linux
- Thunderbird version: 141.0
=> feat(ext): Support dark mode in Preferences
